# Generated by Django 6.0.6 on 2026-06-23 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.TextField()),
                ('mood', models.CharField(max_length=50)),
                ('diagnosis', models.CharField(max_length=200)),
                ('severity', models.CharField(max_length=20)),
                ('success_probability', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation_history', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration_minutes', models.IntegerField()),
                ('start_time', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.panicsession')),
            ],
        ),
    ]
